#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoPickupCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoPlantingCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoGatheringCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoEatingCapabale);