#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoPickupCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoPlantingCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoHoldingCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoEatingCapabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoObstacleCrossingCapable);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_PotatoPlanting_Trigger);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Character_Behaviour_Cooldown_Duration);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_State_HoldingPotato);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Behaviour_State_PotatoPlantingCooldown);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_Behaviour_PotatoRainable);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_State_PotatoPlanting);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_State_PotatoEating);