#include "PotatoGameplayTags.h"
 
UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoPickup_Capabale, "Ability.PotatoPickup.Capabale")
UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoPickup_IsHolding, "Ability.PotatoPickup.IsHolding")

UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoPlanting_Capabale, "Ability.PotatoPlanting.Capabale")
UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoPlanting_Cooldown, "Ability.PotatoPlanting.Cooldown")

UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoEating_Capabale, "Ability.PotatoEating.Capabale")

UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoObstacleCrossing_Capable, "Ability.PotatoObstacleCrossing.Capable")
UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_PotatoObstacleCrossing_Active, "Ability.PotatoObstacleCrossing.Active");

UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Ability_CooldownDuration, "Ability.CooldownDuration")

UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Zone_PotatoPlanting, "Zone.PotatoPlanting")
UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Zone_PotatoEating, "Zone.PotatoEating")

UE_DEFINE_GAMEPLAY_TAG(GameplayTag_Cheat_Ability_PotatoRain_Capable, "Cheat.Ability.PotatoRain.Capable")