#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoPickup_Capabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoPickup_IsHolding);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoPlanting_Capabale);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoPlanting_Cooldown);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoEating_Capabale);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoObstacleCrossing_Capable);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_PotatoObstacleCrossing_Active);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Ability_CooldownDuration);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Zone_PotatoPlanting);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Zone_PotatoEating);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayTag_Cheat_Ability_PotatoRain_Capable);